README.zh_CN.md

Introduce the design, goals, and how to build waylib.

Add the README.zh_CN.md

---

examples/tinywl/main.cpp
src/server/kernel/woutput.cpp
src/server/kernel/wseat.cpp
src/server/kernel/wserver.cpp
src/server/kernel/wserver.h
src/server/kernel/wsurfacelayout.cpp
src/server/kernel/wxdgshell.cpp
src/server/kernel/wxdgsurface.cpp
src/server/qtquick/wsurfaceitem.cpp
src/server/utils/wsignalconnector.cpp
tests/main.cpp

Use the english instead of the Chinese comments

---

examples/tinywl/main.cpp
src/server/kernel/wserver.cpp
src/server/kernel/wserver.h

Use the WServer::displayName for the "WAYLAND_DISPLAY" enviroment
on the tinywl example.

Add "WServer::displayName" interface

---

examples/tinywl/main.cpp
src/server/qtquick/wsurfaceitem.cpp

Always use QSGTexture::Linear mode on render surfaces

---

debian/control

libpixman-1-dev
wayland-protocols

Add build depends for the deb package

---

README.zh_CN.md

From https://github.com/swaywm/wlroots to
https://gitlab.freedesktop.org/wlroots/wlroots

Update the wlroots project url

---

.github/workflows/archlinux-build.yaml

Update build workflow

---

src/server/kernel/woutput.cpp
src/server/kernel/wxdgshell.cpp

Use the "wlr_egl_get_display" instead of "egl->display".
Provide the version when call the "wlr_xdg_shell_create".

Adapt the wlroots 0.16

---

examples/tinywl/main.cpp
src/server/CMakeLists.txt
src/server/kernel/wbackend.cpp
src/server/kernel/woutput.cpp
src/server/kernel/wtexture.cpp
src/server/kernel/wtexture.h

Depends the Qt>=6.4.0, wlroots>=0.16.0.
Needs the follow changes:
https://codereview.qt-project.org/c/qt/qtbase/+/408805 https://codereview.qt-project.org/c/qt/qtdeclarative/+/409621 https://codereview.qt-project.org/c/qt/qtdeclarative/+/411358 https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3532 https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3538
Fixes: #36

Support the vulkan render

---

examples/tinywl/Main.qml
examples/tinywl/main.cpp
src/server/kernel/wbackend.cpp
src/server/kernel/wcursor.cpp
src/server/kernel/wcursor.h
src/server/kernel/winputdevice.h
src/server/kernel/woutputlayout.h
src/server/kernel/wseat.cpp
src/server/kernel/wseat.h
src/server/kernel/wserver.cpp
src/server/kernel/wxdgshell.cpp
src/server/platformplugin/qwlrootswindow.cpp
src/server/platformplugin/qwlrootswindow.h
src/server/qtquick/private/wquickbackend.cpp
src/server/qtquick/private/wquickseat.cpp
src/server/qtquick/private/wquickseat_p.h
src/server/qtquick/private/wquickxdgshell.cpp
src/server/qtquick/woutputrenderwindow.h
src/server/qtquick/wquickcursor.cpp
src/server/qtquick/wquickobserver.cpp
src/server/qtquick/wquickobserver.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

The event receiver order:
1. WSeatEventFilter::eventFilter
2. QWindow
3. QQuickItem
4. WSurfaceItem
5. WSeat::sendEvent
6. wayland clients

Refactor event dispatch system

---

examples/tinywl/Main.qml
examples/tinywl/main.cpp
src/server/CMakeLists.txt
src/server/kernel/private/wserver_p.h
src/server/kernel/private/wsurface_p.h
src/server/kernel/wbackend.h
src/server/kernel/wglobal.h
src/server/kernel/wserver.cpp
src/server/kernel/wserver.h
src/server/kernel/wsocket.cpp
src/server/kernel/wsocket.h
src/server/kernel/wsurface.cpp
src/server/kernel/wsurface.h
src/server/qtquick/private/wquickbackend_p.h
src/server/qtquick/private/wquickseat_p.h
src/server/qtquick/private/wquicksocket.cpp
src/server/qtquick/private/wquicksocket_p.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

Add a attached property to get the socket object from WSurface.
Fixes: #101

Allow add multi socket to WServer

---

examples/tinywl/Main.qml
src/server/kernel/private/wsurface_p.h
src/server/kernel/wsurface.cpp
src/server/kernel/wsurface.h
src/server/kernel/wsurfacehandler.cpp
src/server/kernel/wsurfacehandler.h
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxdgsurface.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

Support xdg surface geometry.
Fix the surface's input region error.

Fix gedit's window position error

---

src/server/kernel/wsocket.cpp

Don't direct use WSocketPrivate* in other class, if the WSocket is destroyed, we will get a invalid pointer of WSocketPrivate in WlClientDestroyListener.

Optimize some codes

---

examples/tinywl/main.cpp
src/server/kernel/woutput.cpp
src/server/kernel/woutput.h
src/server/platformplugin/qwlrootscreen.cpp
src/server/platformplugin/qwlrootscreen.h
src/server/qtquick/private/wqmlhelper.cpp
src/server/qtquick/private/wqmlhelper_p.h
src/server/qtquick/woutputhelper.cpp
src/server/qtquick/woutputhelper.h
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/woutputviewport.cpp
src/server/utils/wtools.cpp
src/server/utils/wtools.h

Add damage ring support for software renderer.
Disable Material style, because this style is bad on software renderer.

Fix crash on software render mode

---

flake.lock

Update qwlroots to fix build with wlroots 17

---

examples/tinywl/OutputDelegate.qml
examples/tinywl/main.cpp
src/server/CMakeLists.txt
src/server/kernel/private/wcursor_p.h
src/server/kernel/wcursor.cpp
src/server/kernel/wcursor.h
src/server/kernel/wseat.cpp
src/server/kernel/wseat.h
src/server/platformplugin/qwlrootswindow.cpp
src/server/platformplugin/qwlrootswindow.h
src/server/platformplugin/types.cpp
src/server/platformplugin/types.h
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/wsurfaceitem.cpp
tests/manual/CMakeLists.txt
tests/manual/pinchhandler/CMakeLists.txt
tests/manual/pinchhandler/Main.qml
tests/manual/pinchhandler/main.cpp
tests/manual/subsurface/Main.qml

close: #99
https://github.com/vioken/waylib/pull/110 status error, can‘t reopen

Support touch event

---

src/server/kernel/wcursor.cpp

client may give an empty cursor surface:
eg:
https://github.com/vioken/waylib/blob/a1e7c5e219aaee984a154cec90b6320dfbf5adf4/tests/manual/cursor/widget.cpp#L32

Don't connect null or outdate surface destroy signal for WCursor

---

examples/tinywl/Main.qml
examples/tinywl/XdgStackWorkspace.qml
examples/tinywl/XdgTiledWorkspace.qml
examples/tinywl/helper.h
examples/tinywl/main.cpp
src/server/kernel/wseat.cpp
src/server/kernel/wseat.h
src/server/qtquick/private/wquickxdgshell.cpp
src/server/qtquick/private/wquickxdgshell_p.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

WSurfaceItem: allow to manual manager size, if you Set ManualResize to WSurfaceItem::resizeMode, the WSurfaceItem's will ignore the WSurface's size change event, and WSurfaceItem's don't set size for WSurface if its size changed.
WXdgSurfaceItem: Add minimumSize maximumSize properties.

tinywl-qtquick: Implementation XdgTiledWorkspace

---

examples/tinywl/Main.qml
src/server/CMakeLists.txt
src/server/qtquick/private/wquickxdgdecorationmanager.cpp
src/server/qtquick/private/wquickxdgdecorationmanager_p.h

Stack layout prefer csd
Tile layout prefer ssd (no decoration now)

Implement XdgDecorationManager 

---

examples/tinywl/XdgStackWorkspace.qml
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxdgsurface.h

need wlr_foreign_toplevel_manager/wlr_layer_shell for wlroots base dock/panal, cann't not test cancel minimize

React to minimize request on XdgStackWorkspace

---

src/server/CMakeLists.txt

treeland build need install this header file

Add missing header kernel/WSurface

---

examples/tinywl/StackWorkspace.qml
src/server/kernel/private/wsurface_p.h
src/server/kernel/wsurface.cpp
src/server/kernel/wsurface.h
src/server/qtquick/private/wquickxwayland.cpp
src/server/qtquick/private/wquickxwayland_p.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

Add surfaceSizeRatio property to WSurfaceItem.
Add parentSurfaceItem property to WXWaylandSurfaceItem.

Support scale WSurfaceItem's size to allow avoid contents fuzzy

---

CMakeLists.txt
examples/tinywl/CMakeLists.txt
flake.nix
nix/default.nix
nix/nixos-test.nix

Usage：
nix flake check -v -L
also work on Garnix CI

Add nixos tinywl test

---

.gitignore
cmake/Helpers.cmake
cmake/WaylandScannerHelpers.cmake
examples/tinywl/Main.qml
src/server/CMakeLists.txt
src/server/kernel/private/wcursor_p.h
src/server/kernel/wcursor.cpp
src/server/kernel/wcursor.h
src/server/qtquick/private/wquickcursorshape.cpp
src/server/qtquick/private/wquickcursorshape_p.h
src/server/qtquick/private/wquickxdgdecorationmanager.cpp

to test:
qtwayland >= 6.6.0
mpv>=0.36.0
foot
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/194
https://github.com/hyprwm/Hyprland/commit/f5913135c638997f8c13a52d0760803947ae3889

Add support for cursor-shape-v1

---

flake.lock
src/server/kernel/woutput.cpp

rect to: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4331

Update qwlroots to fix build with new wlroots-git

---

src/server/qtquick/wrenderhelper.cpp

Remove the codes of copy from wlr_renderer.c

Use "WLR_RENDERER" env variant to create given renderer

---

src/server/kernel/private/wserver_p.h
src/server/kernel/wbackend.cpp
src/server/kernel/wcursor.cpp
src/server/kernel/wseat.cpp
src/server/kernel/wserver.cpp
src/server/kernel/wserver.h
src/server/kernel/wxdgshell.cpp
src/server/kernel/wxwayland.cpp

close: https://github.com/vioken/waylib/issues/154

Make WServerInterface inherit QObject

---

src/cmake/CMakeConfig.cmake.in

Fix config file error in old cmake

---

.github/workflows/archlinux-build.yaml
debian/control
examples/tinywl/CMakeLists.txt
examples/tinywl/LayerSurface.qml
examples/tinywl/Main.qml
examples/tinywl/QmlHelper.qml
examples/tinywl/StackToplevelHelper.qml
examples/tinywl/StackWorkspace.qml
examples/tinywl/TiledWorkspace.qml
examples/tinywl/XdgSurface.qml
examples/tinywl/helper.h
examples/tinywl/main.cpp
flake.lock
flake.nix
nix/default.nix
src/server/CMakeLists.txt
src/server/kernel/WLayerSurface
src/server/kernel/wlayersurface.cpp
src/server/kernel/wlayersurface.h
src/server/kernel/woutput.cpp
src/server/kernel/woutput.h
src/server/kernel/wtoplevelsurface.h
src/server/kernel/wxdgshell.cpp
src/server/qtquick/private/wquicklayershell.cpp
src/server/qtquick/private/wquicklayershell_p.h

close: https://github.com/vioken/waylib/issues/156

Implement Wlr Layer Shell

---

examples/tinywl/LayerSurface.qml
examples/tinywl/StackWorkspace.qml
examples/tinywl/TiledWorkspace.qml
examples/tinywl/main.cpp
flake.lock
flake.nix
src/server/kernel/wxdgshell.cpp
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxdgsurface.h
src/server/qtquick/private/wquickxdgshell.cpp

1. configure layer surface in onEnterOutput maybe too late, Move to Component.onCompleted
2. Support popup'parent is layer surface

Make layer surface support popup

---

examples/tinywl/Main.qml
src/server/CMakeLists.txt
src/server/qtquick/private/winputmethodhelper.cpp
src/server/qtquick/private/winputmethodhelper_p.h
src/server/qtquick/private/wquicktextinputv1.cpp
src/server/qtquick/private/wquicktextinputv1_p.h

Add support for text-input-unstable-v1 which is used by chromium etc.
Log: add text input unstable v1 support

feat: add text input unstable v1 support

---

examples/tinywl/InputPopupSurface.qml
examples/tinywl/Main.qml
examples/tinywl/StackWorkspace.qml
examples/tinywl/TiledWorkspace.qml
src/server/qtquick/private/winputmethodhelper.cpp
src/server/qtquick/private/winputmethodhelper_p.h
src/server/qtquick/private/wquickinputmethodv2.cpp
src/server/qtquick/private/wquickinputmethodv2_p.h

Optimize position and code of input popup surface.
Log: optimize input popup surface

refactor: optimize input popup surface

---

.obs/deepin_workflows.yml
src/server/CMakeLists.txt
src/server/platformplugin/qwlrootsintegration.cpp
src/server/qtquick/private/wbufferrenderer.cpp

Redirect to the FBO of WOutputRenderWindow in render its content item.

Fix QOpenGLContext::defaultFramebufferObject

---

src/server/qtquick/wsurfaceitem.cpp

Revert "WSurfaceItem: release texture after next synchronizing stage"
This reverts commit 4efdfcfd16dd4b057e8c4d917365e0c796bc9a16.

Fix crash on open a popup surface

---

examples/tinywl/Main.qml
examples/tinywl/StackWorkspace.qml
examples/tinywl/TiledWorkspace.qml
examples/tinywl/XdgSurface.qml

1. should not set position in onEnterOutput when surface has in other output
2. alse need consider outputDelegate's position

Fix can't drag surface to other output

---

examples/tinywl/StackWorkspace.qml
examples/tinywl/TiledWorkspace.qml

Fix outputDelegate of xwayland

Fix missing change in workspace

---

flake.lock
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/woutputrenderwindow.h

This will cause topbar not visable when only one output

Fix contentItem size not change after set renderwindow's width/height

---

examples/tinywl/StackToplevelHelper.qml
examples/tinywl/StackWorkspace.qml
src/server/kernel/wtoplevelsurface.h
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxwaylandsurface.cpp
src/server/kernel/wxwaylandsurface.h

Test by weston-fullscreen, foot (wayland), vscode (x11)

Fix not support fullscreen

---

examples/CMakeLists.txt
examples/blur/CMakeLists.txt
examples/blur/Main.qml
examples/blur/main.cpp
src/server/CMakeLists.txt
src/server/kernel/wseat.cpp
src/server/qtquick/private/wbufferrenderer.cpp
src/server/qtquick/private/wbufferrenderer_p.h
src/server/qtquick/private/wqmlhelper.cpp
src/server/qtquick/private/wqmlhelper_p.h
src/server/qtquick/private/wrenderbuffernode.cpp
src/server/qtquick/private/wrenderbuffernode_p.h
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/woutputrenderwindow.h
src/server/qtquick/wrenderbufferblitter.cpp
src/server/qtquick/wrenderbufferblitter.h

You can using the captured buffer do real time Gaussian blur.

Support capture output buffer

---

src/server/qtquick/woutputrenderwindow.cpp

Should get matrix from QQuickItem after QQuickRenderControl::sync.

Fix the render matrix is old

---

src/server/qtquick/private/wquickinputmethodv2.cpp

When InputMethodKeyboardGrabV2::setKeyboard is called, check whether the keyboard is the VirtualKeyboard
of the same client
Issue linuxdeepin/developer-center#6542

Fix duplicate sending of modifiers

---

examples/tinywl/LayerSurface.qml

log: when should set visible for root item

Fix layershell not hide when unmapped

---

examples/tinywl/Main.qml
examples/tinywl/main.cpp

We should use dde-appearance in treeland,

let tinywl read XCURSOR_THEME env to set cursor theme

---

examples/CMakeLists.txt
examples/surface-delegate/CMakeLists.txt
examples/surface-delegate/Main.qml
examples/surface-delegate/main.cpp
examples/tinywl/StackWorkspace.qml
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

1. Allows insert items before or after content item.
2. Allows using cutom item for content item.

Allows to custom SurfaceItem's contents

---

examples/tinywl/main.cpp
src/server/CMakeLists.txt
src/server/qtquick/wrenderhelper.cpp
src/server/qtquick/wrenderhelper.h

forces the creation of a specified renderer if 'WLR_RENDERER' was set

Setup wlr renderer backend

---

src/server/qtquick/private/wqmldynamiccreator.cpp

fix: detect & print error msg on dynamic component creation failure

---

examples/tinywl/LayerSurface.qml
src/server/kernel/wlayersurface.cpp
src/server/kernel/wlayersurface.h
src/server/qtquick/private/wquicklayershell.cpp

1. the property change should be atomic
2. allow close layer surface in qml

Update layer surface wrapper

---

src/server/kernel/wtoplevelsurface.h
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxdgsurface.h
src/server/kernel/wxwaylandsurface.cpp
src/server/kernel/wxwaylandsurface.h

Treeland impl: https://github.com/linuxdeepin/treeland/pull/196

Implement the interface required by the foreign-toplevel protocol for xwayland

---

src/server/qtquick/wsurfaceitem.cpp

it cannot compile with clang++
Log:

fix: warning [-Wformat-extra-args]

---

examples/tinywl/WindowDecoration.qml
examples/tinywl/main.cpp
src/server/kernel/private/wcursor_p.h
src/server/kernel/wcursor.cpp
src/server/kernel/wcursor.h
src/server/qtquick/private/wqmlhelper.cpp

treeland：https://github.com/linuxdeepin/treeland/pull/229

Fix window decoration in touchscreen

---

src/server/kernel/private/wsurface_p.h
src/server/kernel/wlayersurface.cpp
src/server/kernel/wlayersurface.h
src/server/kernel/wsurface.cpp
src/server/kernel/wsurface.h
src/server/kernel/wxdgsurface.cpp
src/server/kernel/wxdgsurface.h

XdgSurface / LayerSurface will reuse wl_surface, some resources like attachedData needs to be instantly reset

Fix wsurface reuse

---

examples/blur/CMakeLists.txt
examples/tinywl/CMakeLists.txt
src/server/CMakeLists.txt

Log: Need link wayland-server, wayland-protocols, pixman-1, xkbcommon, xcb and egl

fix: missing some library links

---

.reuse/dep5
renovate.json

https://zexo.dev/posts/2020/03/01/keep-your-repo-dependencies-up-to-date-with-renovate/
需要：https://github.com/marketplace/renovate

Automate nix and submodules updates with renovate

---

src/server/qtquick/private/wquicklayershell_p.h
src/server/qtquick/private/wquickxdgshell_p.h
src/server/qtquick/private/wquickxwayland_p.h
src/server/qtquick/wsurfaceitem.h

https://github.com/linuxdeepin/treeland/issues/183

Fix content item sync

---

src/server/kernel/wxwaylandsurface.cpp
src/server/qtquick/private/wquickxwayland.cpp

Fix missing titebar (SSD) in treeland

Fix xwayland move form surface and missing WindowTypes

---

examples/tinywl/Main.qml
src/server/CMakeLists.txt
src/server/qtquick/private/wquickscreencopy.cpp
src/server/qtquick/private/wquickscreencopy_p.h

Test by `grim -g "0,0 300x400" -o X11-2 a.png`

Support wlr screen copy

---

cmake/WaylandScannerHelpers.cmake
src/server/CMakeLists.txt
src/server/kernel/wglobal.cpp
src/server/kernel/wglobal.h
src/server/qtquick/private/winputmethodcommon_p.h
src/server/qtquick/private/winputmethodhelper.cpp
src/server/qtquick/private/winputmethodhelper_p.h
src/server/qtquick/private/wquickinputmethodv2.cpp
src/server/qtquick/private/wquickinputmethodv2_p.h
src/server/qtquick/private/wquicktextinputv1.cpp
src/server/qtquick/private/wquicktextinputv1_p.h
src/server/qtquick/private/wquicktextinputv3.cpp
src/server/qtquick/private/wquicktextinputv3_p.h
src/server/qtquick/private/wquickvirtualkeyboardv1.cpp
src/server/qtquick/private/wquickvirtualkeyboardv1_p.h

+ fix cannot generate local protocols
+ extract adaptor from protocols

refact: extract adaptor from protocols

---

examples/tinywl/Main.qml
examples/tinywl/main.cpp
src/server/CMakeLists.txt
src/server/qtquick/private/wquickxdgoutput.cpp
src/server/qtquick/private/wquickxdgoutput_p.h

control wl_client xdgoutput logical_size，Right
now only protocols used by Xwayland are covered.

Xwayland and Wayland synchronized scaling

---

CMakeLists.txt
nix/default.nix
nix/nixos-test.nix
src/server/qtquick/private/wquickxdgoutput.cpp

fix： https://github.com/vioken/waylib/issues/390

Use debug build for nix ci

---

LICENSES/HPND.txt
src/server/CMakeLists.txt
src/server/protocols/private/text-input-unstable-v2.xml
src/server/protocols/private/wtextinputv1_p.h
src/server/protocols/private/wtextinputv2.cpp
src/server/protocols/private/wtextinputv2_p.h
src/server/protocols/winputmethodhelper.cpp

feat: add text input v2 support

---

src/server/CMakeLists.txt
src/server/qtquick/private/wbufferrenderer.cpp
src/server/qtquick/wbuffertextureprovider.h
src/server/qtquick/woutputviewport.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

feat: expose wtexture provider

---

src/server/qtquick/woutputitem.cpp
src/server/qtquick/woutputitem.h
src/server/qtquick/woutputviewport.cpp
src/server/qtquick/woutputviewport.h

When output changes, notify change.

fix: notify output changes

---

src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/woutputrenderwindow.h

Get paint order items from a root.

feat: add utility function in render window

---

src/server/CMakeLists.txt
src/server/platformplugin/qwlrootsintegration.cpp
src/server/platformplugin/qwlrootsintegration.h

QFontconfigDatabase needs nativeInterface()

Fix crash at QFontconfigDatabase::setupFontEngine

---

src/server/kernel/private/wsurface_p.h
src/server/kernel/wserver.cpp
src/server/kernel/wsurface.cpp
src/server/qtquick/wsurfaceitem.cpp

destroy all clients before stop wayland server.

Fix qw_buffe leaks

---

src/server/qtquick/wquickcursor.h
src/server/utils/wcursorimage.cpp

1. fix slot updateImplicitSize not found
2. d->manager not reset when we need load new theme

Fix cursor can't reset

---

src/server/qtquick/woutputrenderwindow.cpp

When starting on multiple screens, newBuffer is null and newBuffer->handle() crashes

Fix crash when booting under multiple screens

---

src/server/kernel/wcursor.cpp

WOutputLayout: : outputRemoved mouse did not update Lead to multiple mouse

Fix Mouse does not update

---

src/server/kernel/wseat.cpp
src/server/qtquick/wquickcursor.cpp
src/server/qtquick/wsurfaceitem.cpp
src/server/utils/wcursorimage.cpp

1. crash in reander when surface isInvalidated
2. client cursor allow setsurface to null

Fix some error in cursor

---

src/server/qtquick/woutputrenderwindow.cpp

When the cursor moves across the screen, the cursor on the first screen is not cleared, need to call set_cursor again to clear it.

fix multiple cursors on multiple screens

---

src/server/utils/wthreadutils.h

fix: typo in macro

---

src/server/CMakeLists.txt
src/server/qtquick/private/wbufferrenderer.cpp
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/woutputrenderwindow.h
src/server/qtquick/woutputviewport.cpp
src/server/qtquick/woutputviewport.h
src/server/qtquick/wsgtextureprovider.cpp
src/server/qtquick/wsgtextureprovider.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h
src/server/qtquick/wtextureproviderprovider.cpp
src/server/qtquick/wtextureproviderprovider.h
src/server/utils/wtools.cpp
src/server/utils/wtools.h

feat: add method to let user grab item

---

src/server/utils/wcursorimage.cpp

close: https://github.com/vioken/waylib/issues/281

Support cursor alternative names form kwin

---

examples/tinywl-new/CMakeLists.txt
examples/tinywl-new/OutputMenuBar.qml
examples/tinywl-new/TitleBar.qml
examples/tinywl-new/WindowMenu.qml
examples/tinywl-new/WorkspaceProxy.qml
examples/tinywl-new/WorkspaceSwitcher.qml
examples/tinywl-new/helper.cpp
examples/tinywl-new/helper.h
examples/tinywl-new/qmlengine.cpp
examples/tinywl-new/qmlengine.h
examples/tinywl-new/surfacewrapper.cpp
examples/tinywl-new/surfacewrapper.h
examples/tinywl-new/wallpaperimage.cpp
examples/tinywl-new/wallpaperimage.h
examples/tinywl-new/workspace.cpp
examples/tinywl-new/workspace.h
examples/tinywl-new/workspacemodel.cpp
examples/tinywl-new/workspacemodel.h

Support Window menu

---

src/server/kernel/wseat.cpp

Reverts vioken/waylib#527
Reason for revert: conversion Error

Revert "fixed horizontal scrolling issue"

---

src/server/qtquick/private/wsurfaceitem_p.h
src/server/qtquick/wsurfaceitem.cpp
src/server/qtquick/wsurfaceitem.h

Move subsurfaces to containers. Use container to control visible.

feat: allow controlling subsurfaces visible

---

src/server/qtquick/private/wsurfaceitem_p.h

Use QPointer to avoid hang pointer.

fix: hang pointer of subsurface container

---

examples/tinywl/helper.cpp
examples/tinywl/output.cpp
examples/tinywl/output.h
src/server/protocols/wxdgpopupsurface.cpp
src/server/protocols/wxdgpopupsurface.h
src/server/protocols/wxdgshell.cpp
src/server/protocols/wxdgshell.h
tests/manual/live/main.cpp

https://github.com/linuxdeepin/treeland.private/pull/504

 feat: support reposition for xdg popup surface 

---

examples/tinywl/output.cpp
examples/tinywl/surfacewrapper.cpp

1. input popup should in cursorRect's bottomLeft
2. fix typo? heightChanged -> implicitHeightChanged

fix: some mistake in tinywl

---

src/server/protocols/private/wtextinputv2.cpp
src/server/protocols/private/wtextinputv2_p.h

Safe connect to before_destroy won't trigger in this case. Connect to aboutToBeInvalidated.

fix: enabled surface not cleared

---

examples/tinywl/output.cpp

The popup will be placed given the details in the passed xdg_positioner object, and a xdg_popup.repositioned *followed by* xdg_popup.configure and xdg_surface.configure will be emitted in response. Any parameters set by the previous positioner will be discarded.

fix: use reposition is to early to arrangePopupSurface

---

src/server/qtquick/wsgtextureprovider.cpp

Acquire texture from client buffer directly instead of invoking wlr_texture_from_buffer.

fix: fail to get texture from client buffer

---

CMakeLists.txt
src/server/kernel/private/woutputlayout_p.h
src/server/kernel/private/wsurface_p.h
src/server/kernel/woutput.cpp
src/server/kernel/woutputlayout.cpp
src/server/protocols/winputpopupsurface.cpp
src/server/protocols/wxdgpopupsurface.cpp
src/server/protocols/wxdgtoplevelsurface.cpp
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/wsgtextureprovider.cpp
src/server/utils/wtools.cpp
src/server/utils/wtools.h

Fix can't disable WAYLIB_USE_PERCOMPILE_HEADERS

---

src/server/qtquick/wrenderhelper.cpp

amend 1d25197d5613210afaa2b9125c9c366f4113a765.

Fix can't auto setup renderer

---

examples/tinywl/surfacewrapper.cpp
src/server/qtquick/private/wbufferrenderer.cpp
src/server/qtquick/private/wbufferrenderer_p.h
src/server/qtquick/woutputrenderwindow.cpp
src/server/qtquick/wquicktextureproxy.cpp

On the virtual machine, maybe compositor will fallback to use the software renderer, and cursor layer is force enable, you will see a black screen on the virtual machine's window.
This issue is testd on VirtualBox.

Fix can't runing on VirtualBox if it not enable 3D accelerate

---

src/server/protocols/winputmethodhelper.cpp

log: https://github.com/linuxdeepin/treeland/issues/369

fix: input popup not update cursorRect before arrange position

---

src/server/qtquick/wsurfaceitem.cpp

This reverts commit 130abe211c6ae8b5a45d025a5875cb202080983e.

Revert "fix: use WWrapPointer instead of QPointer"
