src/server/kernel/wbackend.cpp, src/server/kernel/wcursor.cpp, src/server/kernel/winputdevice.cpp, src/server/kernel/woutput.cpp, src/server/kernel/woutputlayout.cpp, src/server/kernel/wseat.cpp, src/server/kernel/wserver.cpp, src/server/kernel/wsurface.cpp, src/server/kernel/wtexture.cpp, src/server/kernel/wxcursormanager.cpp, src/server/kernel/wxdgshell.cpp, src/server/kernel/wxdgsurface.cpp
Only overwrite the definition of the static keyword when necessary, and
only need to do this if you include the wlroots header file that uses
static.
=> Fix compile errors on archlinux

CMakeLists.txt, cmake/Helpers.cmake, debian/libwaylib-dev.install, src/CMakeLists.txt, src/cmake/CMakeConfig.cmake.in, src/cmake/WaylibConfig.cmake, src/cmake/pkgconfig.pc.in, src/server/CMakeLists.txt
Support use the waylib libraries in cmake/qmake/pkgconfig build system
on other projects. Not create the pri file for qmake, can use the
pkgconfig in qmake.
Resolves: #3
=> Support auto create *.cmake/*.pc files on build

examples/tinywl/CMakeLists.txt, examples/tinywl/Window.qml, examples/tinywl/main.cpp, src/server/kernel/private/wsurfacelayout_p.h, src/server/kernel/wsurface.cpp, src/server/kernel/wsurfacelayout.cpp, src/server/kernel/wsurfacelayout.h
The surface's attached output should follow it's parent surface.
Add a menu widget for the tinywl example.
=> Fix crash on map a popup surface

src/server/kernel/wbackend.cpp, src/server/kernel/woutput.cpp
The wlr_output_init_render should call on the wlr_output_commit before.
=> Fix crash on the drm platform

src/server/kernel/woutput.cpp
When received the hardware cursor's 'frame' signal, must call the
wlr_output_commit to ensure the cursor plane commit to drm.
=> Fix the hardware cursor can't display

src/server/CMakeLists.txt, src/server/kernel/wcursor.cpp, src/server/kernel/woutput.cpp, src/server/kernel/woutput.h, src/server/kernel/woutputdamage.cpp, src/server/kernel/woutputdamage.h, src/server/utils/wtools.cpp, src/server/utils/wtools.h
Use wlr_output_damage for wlr_output. Because can't get the damage
regions from QQuickRenderControl, always to use WOutputDamage::addWhole
now.
fix #30
=> Add WOutputDamage class

examples/tinywl/main.cpp
警告：‘Qt::AA_EnableHighDpiScaling’ is deprecated: High-DPI scaling is always enabled. This attribute no longer has any effect.
警告：‘Qt::AA_UseHighDpiPixmaps’ is deprecated: High-DPI pixmaps are always enabled. This attribute no longer has any effect.
=> Don‘t set deprecated flag in qt6

examples/tinywl/Main.qml, src/server/kernel/woutput.cpp, src/server/kernel/woutput.h, src/server/platformplugin/qwlrootsintegration.cpp, src/server/platformplugin/qwlrootswindow.cpp, src/server/platformplugin/qwlrootswindow.h, src/server/qtquick/woutputhelper.cpp, src/server/qtquick/woutputrenderwindow.cpp
Don't attach render to wlr_output, manager the output buffer in waylib, so we can't cache the QQuickRenderTarget for the wlr_buffer in waylib.
=> Fix the second output no render

examples/tinywl/Main.qml, src/server/CMakeLists.txt, src/server/platformplugin/qwlrootsintegration.cpp, src/server/platformplugin/qwlrootswindow.cpp, src/server/platformplugin/qwlrootswindow.h, src/server/platformplugin/types.h, src/server/qtquick/woutputhelper.cpp, src/server/qtquick/woutputhelper.h, src/server/qtquick/woutputrenderwindow.cpp, src/server/qtquick/woutputrenderwindow.h
If different output have different scale value, and we change the render window when render a part of QtQuick scene graphs at WOutputRenderWindowPrivate::doRender, will lead to QQuickWindow::effectiveDevicePixelRatio changed, so some QQuickItem will update the resources for new device pixel ratio, like as QQuickShaderEffectSource, it will re-create QRhi's texture, this is expensive.
So we keep render window's devicePixelRatio to the maximize scale of multi outputs, don't change it when redner to different viewport, and re-set some properties of QSGRenderer before do render next frame, in order that transform QtQuick scene graphs content to different viewport.
=> Optimize multi outputs

src/server/kernel/wcursor.cpp, src/server/qtquick/woutputrenderwindow.cpp
After https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4295 Must ensure the renderer of wlr_output is initialized before add it to wlr_output_layout and set cursor buffer or xcursor to wlr_cursor.
=> Fix crash at 'assert(renderer != NULL)' in wlroots

src/server/qtquick/woutputviewport.cpp
In the drm backend, must call wlr_output_commit after wlr_output_set_mode and wlr_output_init_render. Maybe it's a bug of wlroots or a bug of Intel gpu driver.
=> Fix wlr_output's commit failed

src/server/qtquick/wsurfaceitem.cpp
wxdgsurface executes deletelater, wlr_surface has been released, but wxdgsurface has not been deleted, if the event loop handles the extrusion event at this time, it will result in a null pointer.
=> Fix crashes caused by mouse events before destructuring

src/server/kernel/wsurface.cpp, src/server/qtquick/wsurfaceitem.cpp
Manager outputs for subsurface in WSurface, auto enter and leave output for subsurface following parent surface.
Fix maybe crash after subsurface removed.
=> Fix subsurface's content freeze

examples/tinywl/Main.qml, examples/tinywl/helper.h, examples/tinywl/main.cpp, src/server/kernel/private/wcursor_p.h, src/server/kernel/wcursor.cpp, src/server/kernel/wcursor.h, src/server/kernel/wseat.cpp, src/server/kernel/wseat.h, src/server/platformplugin/qwlrootswindow.cpp
The new dispatch order of event:
1. WInputDevice
2. WSeat::notify* functions
3. QGuiApplication::sendEvent
4. QWlrootsRenderWindow::windowEvent
5. WSeat::filterInputEvent
6. WOutputRenderWindow::event
7. WSurfaceItem::eventItem
8. WSeat::sendEvent
9. wayland clients
=> Refactor WSeat's policy of event filter

src/server/qtquick/woutputrenderwindow.cpp
If using QQuickRenderTarget to the QQuickWindow, and set true in QQuickRenderTarget::setMirrorVertically, the QQuickWindow will apply flip Y to the matrix with native NDC, this behovior is wrong, If QRhi::isYUpInNDC is true, must ensure the QSGAbstractRenderer::projectionMatrixWithNativeNDC is following QSGAbstractRenderer::projectionMatrix, otherwise must ensure its flip Y relative to QSGAbstractRenderer::projectionMatrix.
See also https://codereview.qt-project.org/c/qt/qtdeclarative/+/499684
=> Fix QML item is missing if its parent enabled clip on vulkan renderer

examples/tinywl/XdgStackWorkspace.qml, src/server/kernel/private/wsurface_p.h, src/server/kernel/wsurface.cpp, src/server/kernel/wsurface.h, src/server/qtquick/private/wqmldynamiccreator.cpp, src/server/qtquick/private/wqmldynamiccreator_p.h, src/server/qtquick/private/wquickxdgshell.cpp, src/server/qtquick/wsurfaceitem.cpp, src/server/qtquick/wsurfaceitem.h
Support add animation when surface removed or close, the WSurfaceItem can lock the last frame buffer of wl_surface, you can using the WSurfaceItem after WSurface destroyed.
=> Allow to delay destroy WSurfaceItem

examples/tinywl/TiledWorkspace.qml, tests/manual/pinchhandler/Main.qml, tests/manual/subsurface/Main.qml
1. Layout.horizontalStretchFactor was introduced in qt 6.5, we can't use in qt 6.4
2. we can use QtQuick.Window in qt 6.4, need apt install qml6-module-qtquick-window in deepin
=> Only set StretchFactor when it's not undefined

src/server/qtquick/wsurfaceitem.cpp, src/server/qtquick/wsurfaceitem.h
If WSurfaceItem::resizeMode is ManualResize, the compositor needs the wlr_surface's implicit size to control the WSurfaceItem's size.
=> WSurfaceItem: support implicitWidth/implicitHeight

src/server/kernel/wbackend.cpp, src/server/kernel/wbackend.h, src/server/kernel/wseat.cpp, src/server/kernel/wseat.h, src/server/kernel/wserver.cpp, src/server/kernel/wserver.h, src/server/kernel/wsocket.cpp, src/server/kernel/wsocket.h, src/server/kernel/wxdgshell.cpp, src/server/kernel/wxdgshell.h, src/server/kernel/wxwayland.cpp, src/server/kernel/wxwayland.h, src/server/qtquick/private/wquickbackend_p.h, src/server/qtquick/private/wquickseat.cpp, src/server/qtquick/private/wquickseat_p.h, src/server/qtquick/private/wquicksocket_p.h, src/server/qtquick/private/wquickxdgdecorationmanager_p.h, src/server/qtquick/private/wquickxdgshell.cpp, src/server/qtquick/private/wquickxdgshell_p.h, src/server/qtquick/private/wquickxwayland.cpp, src/server/qtquick/private/wquickxwayland_p.h, src/server/qtquick/private/wwaylandcompositor_p.h, src/server/qtquick/wquickwaylandserver.cpp, src/server/qtquick/wquickwaylandserver.h
If you want a protocol only visible in a specified socket, you can use WServerInterface::setOwnsSocket now, the WServer will ensure the WServerInterface only visible for the wl_clients connect from the wl_socket of WServerInterface::ownsSocket.
=> Allow specified a owns WSocket to WServerInterface

src/server/qtquick/woutputrenderwindow.cpp
Header wserver.h is not directly used by woutputrenderwindow.cpp. Remove it to remove compile warning.
Log: remove not directly used header
=> chore: remove not directly used header

examples/tinywl/CMakeLists.txt, examples/tinywl/InputPopupSurface.qml, examples/tinywl/Main.qml, examples/tinywl/QmlHelper.qml, examples/tinywl/StackWorkspace.qml, examples/tinywl/TiledWorkspace.qml, examples/tinywl/main.cpp, src/server/CMakeLists.txt, src/server/kernel/wseat.cpp, src/server/kernel/wseat.h, src/server/kernel/wtoplevelsurface.h, src/server/kernel/wxdgsurface.cpp, src/server/kernel/wxdgsurface.h, src/server/qtquick/private/winputmethodhelper.cpp, src/server/qtquick/private/winputmethodhelper_p.h, src/server/qtquick/private/woutputitem_p.h, src/server/qtquick/private/wquickinputmethodv2.cpp, src/server/qtquick/private/wquickinputmethodv2_p.h, src/server/qtquick/private/wquicktextinputv3.cpp, src/server/qtquick/private/wquicktextinputv3_p.h, src/server/qtquick/private/wquickvirtualkeyboardv1.cpp, src/server/qtquick/private/wquickvirtualkeyboardv1_p.h, src/server/qtquick/wquicktextureproxy.cpp
* Implement text-input-unstable-v3.
* Implement input-method-unstable-v2.
* Implement virtual-keyboard-unstable-v1.
* Refactor WToplevelSurface, add property parentSurface, and correct the implementation of parentXdgSurface() in WXdgSurface.
* Add keyboard property and nativeHandle() for WSeat.
* Fix one runtime warning, and add an option to disable the demo client.
=> feat: input method and text input v3 support

CMakeLists.txt
Version 3.21 is strongly recommended for more robust and easy syntax. Version less than 3.5 will soon be out of support.
Log: bump cmake compatibility version
=> chore: bump cmake compatibility version

examples/tinywl/helper.h
These properties in helper.h does not have a read function thus cannot be accessed in qml. We only need its changed signal. Remove these Q_PROPERTY declarations.
Log: remove unused properties
=> chore: remove unused properties

src/server/qtquick/private/winputmethodhelper.cpp
WInputMethodHelper will ignore enabled event of text input v3 when active text input v3 is not disabled yet. This might cause event loss when there are multiple text inputs and the older's disabled event is handled after the newer's enabled event. Just assume the current active text input v3 has been disabled in compositor side. And add check in disabled handler to prevent double deactivate.
Log: fix text input v3 enabled event being ignored
=> fix: text input v3 enabled event being ignored

src/server/CMakeLists.txt
Use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR to avoid path error when compiled as submodule.
Log: fix compilation as submodule
=> fix: compilation as submodule

src/server/platformplugin/qwlrootscreen.cpp
we don't add alpha for QImage's format, it is the same as Xcb.
=> fix: use render_format as wlrootsScreen's format

src/server/kernel/wxdgsurface.cpp
Compositor will crash if xdg_popup has no parent. Check nullptr in
advance.
Log: fix crash when xdg_popup has no parent
=> fix: crash when xdg_popup has no parent

examples/tinywl/Main.qml
Fix input popup surface item not removed due to wrong property name.
Log: fix input popup surface item not removed
=> fix: input popup surface item not removed

examples/tinywl/StackWorkspace.qml, examples/tinywl/XdgSurface.qml
1. check isPopup should use WaylandXdgSurface, not XdgSurfaceItem
2. parent of popup should be parentItem.item, shell(Popup type) is not QQuickItem
3. check popup position do not exceed the screen display area
=> Fix position of popup component

src/server/qtquick/private/wquickinputmethodv2.cpp
InputMethodPopupSurfaceV2's surface might be reused. As previous surface not destroyed, creating a new WSurface from it might cause an owner conflict. Try to find an existent one first.
Log: fix owner conflict when reusing wlr_surface
=> fix: owner conflict when reusing wlr_surface

examples/tinywl/Main.qml, src/server/qtquick/private/wquickbackend.cpp, src/server/qtquick/private/wquickbackend_p.h, src/server/qtquick/woutputrenderwindow.cpp
tinywl: Enable hardware cursor on DRM backend.
=> Fix hardware cursor can't move if content is not repaint

examples/tinywl/OutputDelegate.qml, src/server/qtquick/private/woutputviewport_p.h
Because this is a performance hazard for some GPU architectures (like tiled mobile GPus due to having to reload data onto the on-chip buffer.
=> Disable preserveColorContents on default

examples/tinywl/OutputDelegate.qml
When there are multiple screens, and the scaling factor of the second screen is greater than that of the first screen, if the magnifying glass is activated on the first screen, the automatically calculated size by TextureProxy is incorrect. This leads to an incorrect display area for the proxied OutputViewport.
=> tinywl: Fix magnifying glass on multi outputs

.obs/deepin_workflows.yml
Do not need to build on deepin testing now.
Log: remove unnecessary workflows
=> chore: remove unnecessary workflows

src/server/qtquick/wsurfaceitem.cpp
change focus prop on focusout event will disturb its binding in qml, so disabled.
When disabled, activefocus update may not function before next eventloop, so crash in `doRender -> polishItem`. change to `eventItem->deleteLater` to resolve.
=> Fix WSurfaceItem setFocus

.github/workflows/archlinux-build-wlroots-17.yaml
Add missing base-devel dep
see https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/issues/18
=> fix: archlinux-build-wlroots-17 CI failed on missing debugedit

src/server/kernel/wseat.cpp
Impl auto-repeat keyevents emitting refering to kwin, qtwayland.
Filter out synthetic autorep events in wseat.
Support shortcut auto repeating.
=> feat: support advanced keyboard events (autorepeat)

src/server/qtquick/woutputrenderwindow.cpp
QQuickWindow doesn't automatically gain focus, but ours needs, instead of having to `forceActiveFocus`.
Mimic the behavior of qtquick `ApplicationWindow`
=> Fix: renderwindow auto focus at children items on startup

src/server/qtquick/private/winputmethodhelper.cpp
this may cause random crash
found by @ZhongYic00, this make xwayland unstable after WRenderHelper::setupRendererBackend();
=> fix: uninitialized variable in winputmethodhelper

src/server/qtquick/private/wqmldynamiccreator.cpp, src/server/qtquick/private/wqmldynamiccreator_p.h
Convert QProperty's assigned QVariant<QJSvalue> to QVariantMap, to keep persist with method invoke args.
DynamicCreator's choosorRoleValue can be a js object, dict etc.
=> Fix: convert assigned qjsvalue to QVariantMap

src/server/qtquick/wsurfaceitem.cpp
in https://github.com/vioken/waylib/pull/282 eventItem use deleteLater, parent is null become possible
=> fix: crash when close popup menu

src/server/kernel/wlayersurface.cpp, src/server/kernel/wlayersurface.h
Only configured on creation, so use CONSTANT qproperty
see https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_shell_v1:request:get_layer_surface
=> Feat: expose output specified on creation to qml

src/server/qtquick/wsurfaceitem.cpp, src/server/qtquick/wsurfaceitem.h
item's visible is not enough, should consider itemprivate's ref count.
must use recursiveEffectItemRefcount which refs the whole child item tree.
can't be driven merely by itemChange, check on every output commit
=> Fix: frame done optimization should consider shaderEffectSource etc.

src/server/qtquick/wrenderhelper.cpp
fix crash in wayland backend, backend_destroy will called when wl_display destroy, but never run start_backend
=> fix: backend not start in renderer test

src/server/kernel/wcursor.cpp, src/server/kernel/winputdevice.cpp, src/server/kernel/wlayersurface.cpp, src/server/kernel/woutput.cpp, src/server/kernel/wseat.cpp, src/server/kernel/wsurface.cpp, src/server/kernel/wxdgsurface.cpp, src/server/kernel/wxwaylandsurface.cpp
gtk4 re-use same wsurface for popup, so reset qwsurface's associated owner
fix https://github.com/linuxdeepin/treeland/issues/192
=> Fix: reset qwobj's associated owner to nullptr on destruction

src/server/qtquick/wsurfaceitem.cpp
set surfaceitem's focus to false on destruction.
otherwise, eventItem loses focus, then surfaceItem gets focusIn, and forceActiveFocus to eventItem again
=> Fix surfaceItem crash on destroy

src/server/qtquick/private/wquickseat.cpp, src/server/qtquick/private/wquickseat_p.h
currently only after mouse event can setKeyboardFocusTarget be called to init, prior keyboard is not functioning
=> Fix: add method to init seat's keyboard focus window

src/server/kernel/private/wsurface_p.h, src/server/kernel/wsurface.cpp, src/server/qtquick/wsurfaceitem.cpp, tests/manual/subsurface/Main.qml, tests/manual/subsurface/window.h
Subsurface's surfaceItem itself not actively destroyed, use cases like GTK3 (firefox, d-feet)
=> Fix subsurface destroy

src/server/qtquick/private/wquickcoordmapper.cpp, src/server/qtquick/private/wquickcoordmapper_p.h
Qt 6.7 will perform some actions in the constructor of QQuickItem. Since we provide our own private object, this will cause the target we want to manage not to be initialized in the public object, so the target is moved to the private object for management.
=> Fix LayerShell crash in Qt6.7

src/server/qtquick/wsurfaceitem.cpp
xwayland surfaceItemContent is sized 0x0 since only one commit happens, and the contentContainer is not setSized by the sizeFromSurface policy
=> Fix: xwayland not show since lack initial configure

src/server/qtquick/wsurfaceitem.cpp
-  updateFrameDone when window changed, window may change, or is initialized late
- releaseResources is override func, may be called multiple times both by qt and us
=> Fix firefox popup

examples/tinywl/StackToplevelHelper.qml, examples/tinywl/main.cpp
complement of https://github.com/vioken/waylib/pull/308
> Should sync example/tinywl-qtquick with a new PR.
@ZhongYic00
_Originally posted by @zccrs in https://github.com/vioken/waylib/issues/308#issuecomment-2124321308_
=> Fix: sync tinywl-qtquick to use client-driven resize

src/server/qtquick/woutputlayoutitem.cpp
Fix https://github.com/linuxdeepin/treeland/issues/280
=> fix: In the case of linking the ASAN library, compositor terminate on startup with client.

src/server/qtquick/private/winputmethodhelper.cpp, src/server/qtquick/private/winputmethodhelper_p.h
https://github.com/linuxdeepin/treeland/issues/281
do not use lambda for qt signal & slot
=> fix: Qt ASSERT: QObject::connect: unique connection requires the slot to be a pointer to a member function of a QObject subclass

examples/surface-delegate/Main.qml, examples/tinywl/LayerSurface.qml, examples/tinywl/StackWorkspace.qml, examples/tinywl/TiledWorkspace.qml, examples/tinywl/WindowDecoration.qml, examples/tinywl/XdgSurface.qml, examples/tinywl/main.cpp, src/server/qtquick/private/wquickinputmethodv2.cpp, src/server/qtquick/private/wquickinputmethodv2_p.h, src/server/qtquick/private/wquicklayershell.cpp, src/server/qtquick/private/wquicklayershell_p.h, src/server/qtquick/private/wquickxdgshell.cpp, src/server/qtquick/private/wquickxdgshell_p.h, src/server/qtquick/private/wquickxwayland.cpp, src/server/qtquick/private/wquickxwayland_p.h, src/server/qtquick/wsurfaceitem.cpp, src/server/qtquick/wsurfaceitem.h
- make toplevelSurface a property in WSurfaceItem
- rename `surface`  to `shellSurface` to avoid ambiguity
=> Rename surface in WxxxSurfaceItem to shellsurface

src/server/kernel/wsurface.cpp
"Not need to use safeConnect for the signal of self's handle object"
=> fix: wsurface no need to safeConnect its handle and destroyer

src/server/qtquick/private/wqmldynamiccreator.cpp, src/server/qtquick/private/wqmldynamiccreator_p.h
in order to pass creation arguments to custom qml element (https://github.com/linuxdeepin/treeland/pull/284)
=> feat: set contextProperties of DynamicCreator's delegate in qml

src/server/qtquick/woutputhelper.cpp, src/server/qtquick/woutputhelper.h, src/server/qtquick/woutputrenderwindow.cpp
Frame might have been accepted by old viewport with the same output, if old output viewport is frozen. Then no one will handle frame. Just copy pending state.
=> fix: new output viewport does not render

src/server/qtquick/wquickoutputlayout.cpp
Because setLayout(nullptr) is executed in WOutputLayout::remove, there is no need to set setLayout repeatedly.
=> Fix duplication setting ouput setLayout

src/server/qtquick/wqmlcreator.cpp
Use delete to replace deleteLater() to solve the asynchronous destruction delay problem.
=> Fix Unplug screen crash

src/server/platformplugin/qwlrootscreen.cpp
qt refreshRate mean refresh rate of the screen in Hz, but wlr_output_mode's refresh is mHz.
=> fix: QWlrootsScreen::refreshRate error

src/server/qtquick/private/wbufferrenderer.cpp
update_from_buffer function is using for the pixman image data update to OpenGL texture case, the qw_buffer of WBufferRenderer is allot from qw_swapchain, it's a dmabuf, not needs update_from_buffer after render on this buffer.
=> Drop unnecessary codes

src/server/qtquick/wsurfaceitem.cpp
setParentItem(nullptr) maybe lead to
QQuickDeliveryAgentPrivate::clearFocusInScope, Qt wants emit QQuickItem::window()->focusObjectChanged signal, but the window of that item is nullptr now.
=> Fix crash on application quit

src/server/qtquick/private/wquickcoordmapper.cpp
Destroy WQuickCoordMapper synchronously when item is destroyed
=> Fix crash caused by null pointer

src/server/qtquick/private/wquickcoordmapper.cpp
List.removeOne fails when type conversion using qobject_cast fails at runtime.
=> Use static_cast instead of qobject_cast

examples/tinywl/StackToplevelHelper.qml, examples/tinywl/main.cpp, src/server/kernel/wtoplevelsurface.h, src/server/protocols/wforeigntoplevelv1.cpp, src/server/protocols/wforeigntoplevelv1.h, src/server/protocols/wxdgsurface.cpp, src/server/protocols/wxdgsurface.h, src/server/protocols/wxwaylandsurface.h
1. fix xdg surface never closed by ssd
2. make foreigntoplevelv1 also support xwayland
3. parentSurface is not QObject's parent, and set_parent is not setParent
4. don't emit fake signal for WToplevelSurface
5. use unique_ptr to mange handle to fix handle not delete when surface remove
=> Clear up foreigntoplevelv1 and support xwayland

src/server/protocols/private/wvirtualkeyboardv1.cpp, src/server/protocols/private/wvirtualkeyboardv1_p.h, src/server/protocols/winputmethodhelper.cpp, src/server/protocols/winputmethodhelper.h
Use wlr_virtual_keyboard_v1 directly instead of wrapper for it.
Depends-on: https://github.com/vioken/qwlroots/pull/296
=> fix: virtual keyboard crash in creation

src/server/qtquick/private/wbufferrenderer.cpp
Renderer is delay intialized, so check if renderer is null.
=> fix: crash when setSourceList twice

src/server/qtquick/wquicktextureproxy.cpp
Ensure get image node after set texture provider to SGTextureProviderNode, the image node maybe deleted after setTextureProvider.
=> Fix possible use invalid pointer in WQuickTextureProxy

examples/tinywl-new/qmlengine.cpp
should check whether the imageProvider is successfully registered before registration.
=> Fixed multiple screen crashes

src/server/protocols/private/wtextinputv1.cpp
As there's no method for client to notify server that a text input
v1 should be deleted. Text input here in compositor might be invalid
for client. Do not send enter to text input unless it's activated.
=> fix: qtwayland crash in treeland when enabling im

src/server/qtquick/wquickcursor.cpp
1. Fix https://github.com/linuxdeepin/developer-center/issues/10684
2. Fix
```
wlroots: "[render/gles2/renderer.c:159] Created GL FBO for buffer 24x24"
ASSERT: "texture" in file /home/rewine/deepin-deb/qtdeclarative/src/quick/scenegraph/util/qsgdefaultimagenode.cpp, line 108
Thread 1 "tinywl-qtquick" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: 没有那个文件或目录.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
at ./nptl/pthread_kill.c:44
#1  0x00007ffff4aa715f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff4a59102 in __GI_raise …
```
=> Update ItemHasContents flag before update content

src/server/qtquick/woutputrenderwindow.cpp
Should check if node and filter is null or not.
=> fix: nullptr in paintOrderItems

examples/tinywl/helper.cpp, flake.lock, src/server/protocols/wlayershell.cpp, src/server/protocols/wlayershell.h, src/server/protocols/wxdgshell.cpp, src/server/protocols/wxdgshell.h
When layer_surface is an xdg_popup's parent, the popup should created via xdg_surface::get_popup with the parent set to NULL, and 'zwlr_layer_surface_v1::get_popup' must be invoked before committing the popup's initial state.
We should use parent's `notify_new_popup` to avoid get a popup with NULLparent
=> Fix popup crash when parent is layer surface

examples/tinywl/output.cpp
The internal information of an uninitialized shell surface may not be correct. If configure it at this time, the client will receive an error message. For example, if the layershell surface has no anchor information, its size will be incorrect.
pms: BUG-288905
=> fix: layershell not shown on init

src/server/protocols/winputmethodhelper.cpp, src/server/protocols/winputmethodhelper.h
Separate focused text input and enabled text input. Focused text input corresponds to sendEnter while enabled text input corresponds to enabled event.
=> fix: crash when quickly resend focus

src/server/qtquick/wsurfaceitem.cpp
Buffer update is not controlled by live property. Previous buffer is not refered, thus might be destroyed. Pends new buffer in non-live state.
=> fix: texture invalid in non-live state

src/server/qtquick/private/wbufferrenderer.cpp, src/server/qtquick/private/wbufferrenderer_p.h, src/server/qtquick/private/wrenderbuffernode.cpp
This bug from b9db116d60c1be4417c9871be44543d02bb6741e, on the two outputs if the first output's scale is 1.0 and the second output's scale is 1.5, on the first output, the size of texture from blitter is not equality to the BackdropBlitter's pixel size.
=> Fix BackdropBlitter contents error

src/server/protocols/private/wtextinputv1.cpp
Clear focused surface in sendLeave.
=> fix: focused surface not valid in next activate

src/server/protocols/wforeigntoplevelv1.cpp
```shell
Thread 1 "treeland" received signal SIGSEGV, Segmentation fault.
0x00007f8ac634ba16 in wlr_foreign_toplevel_handle_v1_set_parent (toplevel=0x0, parent=0x0) at ../types/wlr_foreign_toplevel_management_v1.c:477
477             if (parent == toplevel->parent) {
(gdb) bt
#0  0x00007f8ac634ba16 in wlr_foreign_toplevel_handle_v1_set_parent (toplevel=0x0, parent=0x0) at ../types/wlr_foreign_toplevel_management_v1.c:477
#1  0x00007f8ac6913abf in qw_foreign_toplevel_handle_v1::set_parent<decltype(nullptr)>(decltype(nullptr)&&) const (this=0x0)
at /usr/include/qwlroots/qwforeigntoplevelhandlev1.h:49
#2  0x00007f8ac6911bdf in Waylib::Server::WForeignToplevelPrivate::initSurface(Waylib::Server::WToplevelSurface*)::{lambda()#8}::operator()() const
(__closure=0x7ffdfc3eb480) at …
```
=> Fixed the crash when run vlc for the first time

src/server/protocols/private/wtextinputv1.cpp, src/server/protocols/winputmethodhelper.cpp
Do not connect to before_destroy to do something except for deleting
wrap objects. Connect to aboutToBeInvalidated instead. Connect to
before_destroy might face multi-slot sequential problems. Wrap object
might be destroyed already(Safe connections will be disconnected then).
=> fix: before_destroy sequential problems

src/server/kernel/wglobal.h, src/server/kernel/wsurface.cpp, src/server/protocols/wlayershell.cpp, src/server/qtquick/wsurfaceitem.cpp
SafeConnect does not work correctly when connecting to QObject's signal and qw_object_basic::before_destroy. Do not use it to connect to QObject::destroyed signal and forward to QObject::connect when connecting to before_destroy.
=> fix: safeConnect instantiation error

src/server/protocols/wxdgpopupsurface.cpp
When a popup appears or is clicked we should give focus to its parent. If the popup gets focus independently,  it will not be give focus to the parent after closing.
=> fix: toplevel lose fouse when click popup

src/server/protocols/private/wtextinputv2.cpp, src/server/protocols/winputmethodhelper.cpp, src/server/protocols/winputmethodhelper.h
* fix input method not correctly destroyed
* fix text input v2 do not clear focused surface
=> fix: some problems in input method

src/server/qtquick/private/wrenderbuffernode.cpp
Disable DepthAwareRendering to ensure the uniform render order as element order.
=> fix: wrong z order of render buffer blitter

src/server/qtquick/private/wrenderbuffernode.cpp
CurrentRenderer may be null, if it's null, disable depth test.
=> fix: crash when determine force depth test

src/server/qtquick/wsurfaceitem.cpp
```
#0  0x00007f5e8f8d42f0 in Waylib::Server::WSurfaceItemContent::bufferOffset() const () at /usr/bin/../lib/x86_64-linux-gnu/libwaylibserver.so.0
#1  0x00007f5e8f906608 in QtPrivate::QCallableObject<Waylib::Server::WQuickCursorPrivate::setSurface(Waylib::Server::WSurface*)::{lambda()#1}, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) () at /usr/bin/../lib/x86_64-linux-gnu/libwaylibserver.so.0
#2  0x00007f5e8f24096c in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
#3  0x00007f5e8f8dc128 in Waylib::Server::WSurfaceItemContentPrivate::updateSurfaceState() () at /usr/bin/../lib/x86_64-linux-gnu/libwaylibserver.so.0
#4  0x00007f5e8f24096c in ??? () at /usr/bin/../lib/x86_64-linux-gnu/libQt6Core.so.6
#5  0x00007f5e8cfc7afc in …
```
=> fix: use WWrapPointer instead of QPointer

.github/workflows/archlinux-build-wlroots-18.yaml, src/server/platformplugin/qwlrootsintegration.cpp, src/server/qtquick/wqmlcreator.cpp
Qt renamed QGenericUnixServices on 6.9+:
https://github.com/qt/qtbase/commit/3e29267df0e2f332290caad69e5bd5cfd61cf3da
The fix for
https://github.com/qt/qtdeclarative/commit/2f35c7036e468d97ace2a5b3987674a30d29d532
wasn't cherry-picked into 6.9.0. Let's change it to target 6.10.0 for
now.
Also fix CI for Arch Linux.
=> fix: compatibility with Qt 6.9+
